spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Alibou

server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: alibou-rest-api
      principle-attribute: preferred_username
